#pragma once

#include "bridge_core_export.h"

#define BUBRIDGE_LIVESYNC_PROTOCOL_VERSION "0.1.0"
#define BUBRIDGE_LIVESYNC_DEFAULT_PORT 27284
#define BUBRIDGE_LIVESYNC_DEFAULT_HOST "127.0.0.1"

#define BUBRIDGE_MSG_HELLO "HELLO"
#define BUBRIDGE_MSG_HELLO_ACK "HELLO_ACK"
#define BUBRIDGE_MSG_GOODBYE "GOODBYE"
#define BUBRIDGE_MSG_KEEPALIVE "KEEPALIVE"
#define BUBRIDGE_MSG_OBJECT_TRANSFORM_UPDATE "OBJECT_TRANSFORM_UPDATE"
