"""
Blender Unreal Bridge - Version Information
"""

VERSION_MAJOR = 0
VERSION_MINOR = 1
VERSION_PATCH = 0

VERSION = (VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH)
VERSION_STRING = f"{VERSION_MAJOR}.{VERSION_MINOR}.{VERSION_PATCH}"

FORMAT_NAME = "BUBRIDGE"
FORMAT_VERSION = VERSION_STRING
